// RAIDEX_LEGAL_PRIVACY
// Static Privacy Policy screen. DRAFT product-authored copy pending real
// legal review. Every data-collection/storage/sharing claim here is meant to
// trace back to real behavior in backend/server.py, backend/providers/
// kyc_provider.py and backend/providers/payment_gateway.py - not invented.
import React from "react";
import { LegalScreen, LegalSection, LegalParagraph, LegalBullet, LegalSubheading } from "@/src/components/legal/LegalScreen";

export default function PrivacyPolicy() {
  return (
    <LegalScreen title="Privacy Policy" lastUpdated="14 September 2026" testID="privacy-screen">
      <LegalParagraph>
        This Privacy Policy explains what personal information Raidex collects when you use the app, why we
        collect it, how it is stored, and who it is shared with. Raidex is a vehicle-rental marketplace, so
        some of what we collect — particularly KYC documents — exists to meet identity-verification and
        regulatory expectations for rental platforms, not just to run the app.
      </LegalParagraph>

      <LegalSection title="1. Information we collect">
        <LegalSubheading>Account information</LegalSubheading>
        <LegalBullet>Name, email address, and password (stored as a bcrypt hash, never in plain text) for email sign-up</LegalBullet>
        <LegalBullet>Phone number, for phone/OTP sign-in</LegalBullet>
        <LegalSubheading>KYC documents</LegalSubheading>
        <LegalBullet>Aadhaar card images (front and back) and the last 4 digits of your Aadhaar number</LegalBullet>
        <LegalBullet>Driving licence images (front and back), licence number, and expiry date</LegalBullet>
        <LegalBullet>A live selfie photo, used to match your face against your Aadhaar photo</LegalBullet>
        <LegalSubheading>Trip and location data</LegalSubheading>
        <LegalBullet>GPS location, collected only while you have an active trip in progress, to track the rented vehicle and support safety and fleet operations</LegalBullet>
        <LegalBullet>Odometer readings and inspection photos taken at the start and end of a trip</LegalBullet>
        <LegalSubheading>Payment and rewards data</LegalSubheading>
        <LegalBullet>Payment amount, status, and identifiers returned by our payment gateway — Raidex itself does not receive or store your full card, UPI, or bank account number</LegalBullet>
        <LegalBullet>Wallet balance and RideMiles rewards balance, and the transaction history behind each</LegalBullet>
        <LegalSubheading>Device and usage data</LegalSubheading>
        <LegalBullet>Basic device and app-usage information generated by using a mobile app (e.g. crash/error diagnostics), where enabled</LegalBullet>
      </LegalSection>

      <LegalSection title="2. Why we collect it">
        <LegalBullet>To create and secure your account, and to let you sign in</LegalBullet>
        <LegalBullet>To verify your identity before you can book a vehicle, as required for a rental marketplace and consistent with Indian KYC norms</LegalBullet>
        <LegalBullet>To process bookings, payments, refunds, and deposits</LegalBullet>
        <LegalBullet>To track an active trip for safety, recovery, and support purposes</LegalBullet>
        <LegalBullet>To detect fraud, resolve disputes, and investigate misuse</LegalBullet>
        <LegalBullet>To operate rewards (RideMiles) and your in-app wallet</LegalBullet>
      </LegalSection>

      <LegalSection title="3. How your information is stored and secured">
        <LegalParagraph>
          KYC document images are stored in a dedicated document store (GridFS) separate from your everyday
          account record, rather than sitting alongside your profile data. Passwords are hashed with bcrypt and
          are never stored or logged in plain text. Signed-in sessions use signed authentication tokens (JWT)
          that expire automatically. Sensitive account and financial actions are rate-limited to reduce abuse.
          No storage system is perfectly secure, and this section describes our intended practices rather than
          a guarantee.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="4. Who we share it with">
        <LegalBullet>A KYC verification provider, to check your Aadhaar and driving licence and perform face matching — this may be an automated in-house check or a licensed third-party KYC verification service, depending on configuration</LegalBullet>
        <LegalBullet>A payment gateway (Razorpay, when live payments are enabled), to process payments and refunds — Raidex passes the amount to be charged and receives back a payment status and reference id, not your card/bank details</LegalBullet>
        <LegalBullet>The vehicle owner for a given booking, limited to what they reasonably need to hand over the vehicle (e.g. your name and booking details) — not your KYC documents or full contact details</LegalBullet>
        <LegalBullet>Raidex's own support and operations staff, when needed to resolve a support request or a dispute you raised</LegalBullet>
        <LegalBullet>Law enforcement or regulators, where legally required</LegalBullet>
        <LegalParagraph>
          Raidex does not sell your personal information.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="5. Data retention">
        <LegalParagraph>
          We retain KYC documents and booking/payment records for as long as your account is active and for
          the additional period needed to meet identity-verification, tax/GST record-keeping, and dispute-
          resolution obligations. Wallet and RideMiles ledger history is retained as part of your account
          history. If you close your account, we will delete or anonymize personal information that we are no
          longer required to keep.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="6. Your rights and choices">
        <LegalParagraph>
          You can view your KYC status, wallet balance, and RideMiles history at any time inside the app. You
          can request correction of inaccurate profile information, and you can request a copy or deletion of
          your personal data, by contacting us using the details below. Raidex does not currently offer a fully
          self-serve "delete my account" button in the app — account deletion today is handled by our support
          team on request, subject to the retention needs described in Section 5.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="7. Children's privacy">
        <LegalParagraph>
          Raidex is not directed at, and is not intended for use by, anyone under 18 — bookings require a valid
          driving licence and adult KYC documents. We do not knowingly collect personal information from
          children.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="8. Changes to this policy">
        <LegalParagraph>
          We may update this Privacy Policy as our data practices evolve. Material changes will update the
          "Last updated" date above.
        </LegalParagraph>
      </LegalSection>

      <LegalSubheading>Contact us about privacy</LegalSubheading>
      <LegalParagraph>
        privacy@raidex.example (placeholder contact — to be replaced with a real privacy/support address
        before launch) · [Raidex Technologies Pvt. Ltd. — registered address to be added]
      </LegalParagraph>
    </LegalScreen>
  );
}
